# Generated by Django 2.1.1 on 2018-09-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
